CUFILES         := blas_quda.cu
CCFILES         := inv_bicgstab_quda.cpp inv_cg_quda.cpp blas_reference.cpp

CUDA_INSTALL_PATH = /usr/local/cuda
INCLUDES = -I. -I$(CUDA_INSTALL_PATH)/include
LIB = -L$(CUDA_INSTALL_PATH)/lib -lcudart

DFLAGS = #-D__DEVICE_EMULATION__

CC = gcc
CFLAGS = -Wall -O3 -std=c99 $(INCLUDES) ${DFLAGS}
CXX = g++
CXXFLAGS = -Wall -O3 $(INCLUDES) ${DFLAGS} 
NVCC = $(CUDA_INSTALL_PATH)/bin/nvcc 
NVCCFLAGS = -O3 $(INCLUDES) ${DFLAGS} -arch=sm_13 #-deviceemu
LDFLAGS = -fPIC $(LIB)

all: dslash_test invert_test

ILIB = libquda_dwf.a
ILIB_OBJS = dslash_quda.o blas_quda.o util_quda.o \
	gauge_quda.o spinor_quda.o invert_quda.o dslash_reference.o \
  myerror.o inv_cg_quda.o inv_bicgstab_quda.o blas_quda.o blas_reference.o

ILIB_DEPS = $(ILIB_OBJS) blas_quda.h quda.h util_quda.h gauge_quda.h \
  spinor_quda.h enum_quda.h invert_quda.h dslash_reference.h

$(ILIB): $(ILIB_DEPS)
	ar cru $@ $(ILIB_OBJS)

dslash_test: dslash_test.o $(ILIB)
	$(CXX) $(LDFLAGS) $< $(ILIB) -o $@

invert_test: invert_test.o $(ILIB)
	$(CXX) $(LDFLAGS) $< $(ILIB) -o $@


clean:
	-rm -f *.o dslash_test invert_test $(ILIB)

%.o: %.c
	$(CC) $(CFLAGS) $< -c -o $@

%.o: %.cpp
	$(CXX) $(CXXFLAGS) $< -c -o $@

%.o: %.cu
	$(NVCC) $(NVCCFLAGS) $< -c -o $@

