//
// Auto-tuned blas CUDA parameters, generated by blas_test
//

<<<<<<< HEAD
static int blas_threads[30][3] = {
  {  64,  512,   64},  // Kernel  0: copyCuda (high source precision)
  { 576,  544,  320},  // Kernel  1: copyCuda (low source precision)
  {  96,  128,  128},  // Kernel  2: axpbyCuda
  { 160,  128,  128},  // Kernel  3: xpyCuda
  { 160,  448,  128},  // Kernel  4: axpyCuda
  {  96,  128,  128},  // Kernel  5: xpayCuda
  { 160,  128,  128},  // Kernel  6: mxpyCuda
  { 192,  448,  640},  // Kernel  7: axCuda
  {  64,  128,   96},  // Kernel  8: caxpyCuda
  {  96,  128,   64},  // Kernel  9: caxpbyCuda
  {  96,   96,   96},  // Kernel 10: cxpaypbzCuda
  { 448,   64,   64},  // Kernel 11: axpyBzpcxCuda
  { 512,   64,   64},  // Kernel 12: axpyZpbxCuda
  {  64,   96,   64},  // Kernel 13: caxpbypzYmbwCuda
  { 128,  256,  256},  // Kernel 14: normCuda
  { 128,  128,  256},  // Kernel 15: reDotProductCuda
  { 256,  256,  512},  // Kernel 16: axpyNormCuda
  { 256,  256,  512},  // Kernel 17: xmyNormCuda
  { 128,  128,  512},  // Kernel 18: cDotProductCuda
  { 256,  256,  256},  // Kernel 19: xpaycDotzyCuda
  { 128,  128,  128},  // Kernel 20: cDotProductNormACuda
  { 128,  128,  128},  // Kernel 21: cDotProductNormBCuda
  { 256,  256,  256},  // Kernel 22: caxpbypzYmbwcDotProductWYNormYCuda
  { 128,  128,   64},  // Kernel 23: cabxpyAxCuda
  { 256,  256,  256},  // Kernel 24: caxpyNormCuda
  { 256,  256,  256},  // Kernel 25: caxpyXmazNormXCuda
  { 256,  512,  256},  // Kernel 26: cabxpyAxNormCuda
  {  64,  128,  256},  // Kernel 27: caxpbypzCuda
  {  64,  128,  128},  // Kernel 28: caxpbypczpwCuda
  { 256,  128,  256}   // Kernel 29: caxpyDotzyCuda
};

static int blas_blocks[30][3] = {
  { 4096,   512,  8192},  // Kernel  0: copyCuda (high source precision)
  { 8192,  1024, 65536},  // Kernel  1: copyCuda (low source precision)
  { 2048, 16384, 65536},  // Kernel  2: axpbyCuda
  { 1024, 16384, 65536},  // Kernel  3: xpyCuda
  { 1024,  4096, 32768},  // Kernel  4: axpyCuda
  { 2048, 16384, 32768},  // Kernel  5: xpayCuda
  { 1024, 16384, 32768},  // Kernel  6: mxpyCuda
  { 1024,  4096,  8192},  // Kernel  7: axCuda
  { 2048, 65536, 65536},  // Kernel  8: caxpyCuda
  { 2048, 32768, 32768},  // Kernel  9: caxpbyCuda
  { 2048, 32768, 65536},  // Kernel 10: cxpaypbzCuda
  {  512, 32768, 32768},  // Kernel 11: axpyBzpcxCuda
  {  512, 32768, 32768},  // Kernel 12: axpyZpbxCuda
  { 4096, 65536, 65536},  // Kernel 13: caxpbypzYmbwCuda
  {   64,   256,  1024},  // Kernel 14: normCuda
  {  256,  1024,  1024},  // Kernel 15: reDotProductCuda
  { 2048,    64,  4096},  // Kernel 16: axpyNormCuda
  {65536,    64,  4096},  // Kernel 17: xmyNormCuda
  {  128,   512,   128},  // Kernel 18: cDotProductCuda
  {  512,  1024,  2048},  // Kernel 19: xpaycDotzyCuda
  {  128,   512,   512},  // Kernel 20: cDotProductNormACuda
  {  128,   512,  1024},  // Kernel 21: cDotProductNormBCuda
  {  512,   512,  1024},  // Kernel 22: caxpbypzYmbwcDotProductWYNormYCuda
  { 2048, 32768, 32768},  // Kernel 23: cabxpyAxCuda
  {  512,  2048,  2048},  // Kernel 24: caxpyNormCuda
  { 2048,  2048,  4096},  // Kernel 25: caxpyXmazNormXCuda
  { 2048,  2048,  4096},  // Kernel 26: cabxpyAxNormCuda
  { 4096, 65536, 32768},  // Kernel 27: caxpbypzCuda
  { 4096, 65536, 32768},  // Kernel 28: caxpbypczpwCuda
  {  512,  1024,  1024}   // Kernel 29: caxpyDotzyCuda
=======
static int blas_threads[31][3] = {
  { 256,  192,  256},  // Kernel  0: copyHS
  { 256,  256,  256},  // Kernel  1: copyLS
  { 192,   64,   64},  // Kernel  2: axpby
  { 192,   64,   64},  // Kernel  3: xpy
  { 192,   64,   64},  // Kernel  4: axpy
  { 192,   64,   64},  // Kernel  5: xpay
  { 256,   64,   64},  // Kernel  6: mxpy
  { 256,   64,   64},  // Kernel  7: ax
  { 192,   64,   64},  // Kernel  8: caxpy
  { 192,   64,   64},  // Kernel  9: caxpby
  { 160,   32,   32},  // Kernel 10: cxpaypbz
  { 128,  192,  160},  // Kernel 11: axpyBzpcx
  { 128,  192,  160},  // Kernel 12: axpyZpbx
  { 256,   64,   32},  // Kernel 13: caxpbypzYmbw
  { 256,   32,   32},  // Kernel 14: cabxpyAx
  { 128,   32,   32},  // Kernel 15: caxpbypz
  { 256,   32,   32},  // Kernel 16: caxpbypczpw
  { 128,  192,  160},  // Kernel 17: caxpyXmaz
  { 128,  160,  192},  // Kernel 18: norm
  {  96,   96,   64},  // Kernel 19: reDotProduct
  { 192,   64,   64},  // Kernel 20: axpyNorm
  { 192,   64,   64},  // Kernel 21: xmyNorm
  { 192,   64,   64},  // Kernel 22: caxpyNorm
  { 128,   32,   32},  // Kernel 23: caxpyXmazNormX
  { 256,   32,   32},  // Kernel 24: cabxpyAxNorm
  { 128,  256,  256},  // Kernel 25: cDotProduct
  { 128,   32,   32},  // Kernel 26: xpaycDotzy
  { 128,   32,   32},  // Kernel 27: caxpyDotzy
  { 128,  160,  160},  // Kernel 28: cDotProductNormA
  {  96,  160,  192},  // Kernel 29: cDotProductNormB
  { 224,   32,   32}   // Kernel 30: caxpbypzYmbwcDotProductWYNormY
};

static int blas_blocks[31][3] = {
  {  192,   202,   246},  // Kernel  0: copyHS
  {  216,   155,   206},  // Kernel  1: copyLS
  {  254,    77,    65},  // Kernel  2: axpby
  {  223,    92,    69},  // Kernel  3: xpy
  {  221,    81,    64},  // Kernel  4: axpy
  {  211,    89,    78},  // Kernel  5: xpay
  {  195,    97,    64},  // Kernel  6: mxpy
  {  150,   108,   106},  // Kernel  7: ax
  {  255,    94,    80},  // Kernel  8: caxpy
  {  256,    94,    78},  // Kernel  9: caxpby
  {  239,   112,   112},  // Kernel 10: cxpaypbz
  {  248,    16,    16},  // Kernel 11: axpyBzpcx
  {  226,    16,    16},  // Kernel 12: axpyZpbx
  {   27,   146,   150},  // Kernel 13: caxpbypzYmbw
  {  248,    99,    91},  // Kernel 14: cabxpyAx
  {  237,   110,   109},  // Kernel 15: caxpbypz
  {  176,    97,    97},  // Kernel 16: caxpbypczpw
  {  169,    16,    16},  // Kernel 17: caxpyXmaz
  {   64,    96,    80},  // Kernel 18: norm
  {   55,   112,   110},  // Kernel 19: reDotProduct
  {  132,    94,    76},  // Kernel 20: axpyNorm
  {  125,    94,    77},  // Kernel 21: xmyNorm
  {  178,    79,    82},  // Kernel 22: caxpyNorm
  {  225,    93,    77},  // Kernel 23: caxpyXmazNormX
  {  211,    97,    94},  // Kernel 24: cabxpyAxNorm
  {   42,    42,    42},  // Kernel 25: cDotProduct
  {  223,   107,   108},  // Kernel 26: xpaycDotzy
  {  251,   112,   112},  // Kernel 27: caxpyDotzy
  {   49,    56,    56},  // Kernel 28: cDotProductNormA
  {   69,    56,    42},  // Kernel 29: cDotProductNormB
  {  157,    78,    97}   // Kernel 30: caxpbypzYmbwcDotProductWYNormY
>>>>>>> master
};
